"""
GovPlot Tracker — Static Schemes v4.0
======================================
Comprehensive static schemes for all 20 cities.
Used as:
  1. Initial dataset on website launch (before scrapers run)
  2. Fallback data when live scraping fails

RULES:
  - Only Govt residential plot lottery schemes
  - No e-auction, no LIG/MIG/EWS flat schemes
  - price_min >= 25.0 (₹25L minimum)
  - Schemes from HTML report only — no extras
  - data_source = "STATIC"
  - scraper_status = "fallback"
"""

from __future__ import annotations
from datetime import datetime, timezone


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ─────────────────────────────────────────────────────────────────────────────
# STATIC SCHEMES — 20 Cities, 3-5 schemes each
# ─────────────────────────────────────────────────────────────────────────────

STATIC_SCHEMES: list[dict] = [

    # ═══════════════════════════════════════════════════════════════════
    # 1. GREATER NOIDA / YEIDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "YEIDA-RPS10-2026",
        "name": "YEIDA Sector 18 Yamuna Expressway Residential Plot Lottery 2026 (RPS10/2026)",
        "city": "Greater Noida",
        "authority": "YEIDA",
        "status": "UPCOMING",
        "open_date": "2026-06-01",
        "close_date": "2026-08-31",
        "total_plots": 2000,
        "price_min": 30.0,
        "price_max": 90.0,
        "area_sqft_min": 1740,  # 162 sqm
        "area_sqft_max": 3120,  # 290 sqm
        "location_details": "Sector 18, Yamuna Expressway — near Jewar Airport",
        "apply_url": "https://yamunaexpresswayauthority.com",
        "source_url": "https://yamunaexpresswayauthority.com/scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "YEIDA-RPS10-2025-JUL",
        "name": "YEIDA Sector 24A Residential Plot Lottery 2025 (RPS10/2025) — 54,000+ Applied",
        "city": "Greater Noida",
        "authority": "YEIDA",
        "status": "CLOSED",
        "open_date": "2025-04-21",
        "close_date": "2025-06-30",
        "total_plots": 276,
        "price_min": 28.0,
        "price_max": 75.0,
        "area_sqft_min": 2152,  # 200 sqm
        "area_sqft_max": 2152,
        "location_details": "Sector 24A, Yamuna Expressway",
        "apply_url": "https://yamunaexpresswayauthority.com",
        "source_url": "https://yamunaexpresswayauthority.com/scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "YEIDA-RPS08A-2024-NOV",
        "name": "YEIDA Diwali 2024 Residential Plot Lottery (RPS08A/2024) — 1L+ Applied",
        "city": "Greater Noida",
        "authority": "YEIDA",
        "status": "CLOSED",
        "open_date": "2024-10-31",
        "close_date": "2024-11-30",
        "total_plots": 451,
        "price_min": 25.0,
        "price_max": 72.0,
        "area_sqft_min": 1292,  # 120 sqm
        "area_sqft_max": 2690,  # 250 sqm
        "location_details": "Sector 24A, Yamuna Expressway — near Jewar Airport",
        "apply_url": "https://yamunaexpresswayauthority.com",
        "source_url": "https://yamunaexpresswayauthority.com/scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "YEIDA-RPS08-2024-JUL",
        "name": "YEIDA Airport Zone Residential Plot Lottery 2024 (RPS08/2024) — 2L+ Applied",
        "city": "Greater Noida",
        "authority": "YEIDA",
        "status": "CLOSED",
        "open_date": "2024-07-01",
        "close_date": "2024-08-23",
        "total_plots": 363,
        "price_min": 25.0,
        "price_max": 68.0,
        "area_sqft_min": 1292,
        "area_sqft_max": 2690,
        "location_details": "Sector near NIA Jewar Airport, Yamuna Expressway",
        "apply_url": "https://yamunaexpresswayauthority.com",
        "source_url": "https://yamunaexpresswayauthority.com/scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 2. LUCKNOW / LDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "LDA-ANANT-NAGAR-PHASE3-2025",
        "name": "LDA Anant Nagar Yojna Phase 3 Residential Plot Lottery 2025",
        "city": "Lucknow",
        "authority": "LDA",
        "status": "OPEN",
        "open_date": "2025-12-20",
        "close_date": "2026-04-30",
        "total_plots": 600,
        "price_min": 40.0,
        "price_max": 120.0,
        "area_sqft_min": 1200,  # 112.5 sqm
        "area_sqft_max": 4844,  # 450 sqm
        "location_details": "Anant Nagar Township, Mohan Road / Kakori Road, Lucknow",
        "apply_url": "https://www.ldalucknow.in",
        "source_url": "https://www.ldalucknow.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "LDA-ANANT-NAGAR-PHASE2-2025",
        "name": "LDA Anant Nagar Yojna Phase 2 Residential Plot Lottery 2025 — 8,568 Applied",
        "city": "Lucknow",
        "authority": "LDA",
        "status": "CLOSED",
        "open_date": "2025-07-11",
        "close_date": "2025-08-10",
        "total_plots": 332,
        "price_min": 37.0,
        "price_max": 95.0,
        "area_sqft_min": 1200,
        "area_sqft_max": 2152,
        "location_details": "Anant Nagar Township, Mohan Road, Lucknow",
        "apply_url": "https://www.ldalucknow.in",
        "source_url": "https://www.ldalucknow.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "LDA-VRINDAVAN-YOJANA-2026",
        "name": "LDA Vrindavan Yojana Residential Plot Lottery 2026",
        "city": "Lucknow",
        "authority": "LDA",
        "status": "UPCOMING",
        "open_date": "2026-06-01",
        "close_date": "2026-08-31",
        "total_plots": 480,
        "price_min": 35.0,
        "price_max": 95.0,
        "area_sqft_min": 1200,
        "area_sqft_max": 3600,
        "location_details": "Vrindavan Yojana, Lucknow",
        "apply_url": "https://www.ldalucknow.in",
        "source_url": "https://www.ldalucknow.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 3. JAIPUR / JDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "JDA-GANGA-YAMUNA-SARASWATI-2025",
        "name": "JDA Ganga Vihar / Yamuna Vihar / Saraswati Vihar Residential Plot Lottery 2025",
        "city": "Jaipur",
        "authority": "JDA",
        "status": "CLOSED",
        "open_date": "2025-05-13",
        "close_date": "2025-06-16",
        "total_plots": 765,
        "price_min": 30.0,
        "price_max": 100.0,
        "area_sqft_min": 540,
        "area_sqft_max": 3240,
        "location_details": "Daultpura, Chaksu, Bassi — Jaipur periphery",
        "apply_url": "https://jda.rajasthan.gov.in",
        "source_url": "https://jda.rajasthan.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "JDA-GOVIND-VIHAR-2024",
        "name": "JDA Govind Vihar Yojana Residential Plot Lottery 2024–25 — 1,32,855 Applied",
        "city": "Jaipur",
        "authority": "JDA",
        "status": "CLOSED",
        "open_date": "2024-12-18",
        "close_date": "2025-01-17",
        "total_plots": 250,
        "price_min": 28.0,
        "price_max": 90.0,
        "area_sqft_min": 540,
        "area_sqft_max": 3240,
        "location_details": "Govindpura Ropada, near Khatipura Railway Station, Jaipur",
        "apply_url": "https://jda.rajasthan.gov.in",
        "source_url": "https://jda.rajasthan.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "JDA-ATAL-VIHAR-2024",
        "name": "JDA Atal Vihar Yojana Residential Plot Lottery 2024–25 — 83,274 Applied",
        "city": "Jaipur",
        "authority": "JDA",
        "status": "CLOSED",
        "open_date": "2024-12-18",
        "close_date": "2025-01-17",
        "total_plots": 200,
        "price_min": 30.0,
        "price_max": 100.0,
        "area_sqft_min": 540,
        "area_sqft_max": 3240,
        "location_details": "Kalwad Road, Jaipur",
        "apply_url": "https://jda.rajasthan.gov.in",
        "source_url": "https://jda.rajasthan.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "JDA-NEW-SCHEME-2025",
        "name": "JDA New Residential Plot Scheme 2025–26 (Upcoming — 3 Schemes)",
        "city": "Jaipur",
        "authority": "JDA",
        "status": "UPCOMING",
        "open_date": "2026-01-01",
        "close_date": "2026-03-31",
        "total_plots": 800,
        "price_min": 32.0,
        "price_max": 110.0,
        "area_sqft_min": 540,
        "area_sqft_max": 3240,
        "location_details": "Multiple zones, Jaipur",
        "apply_url": "https://jda.rajasthan.gov.in",
        "source_url": "https://jda.rajasthan.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 4. AGRA / ADA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "ADA-ATALPURAM-PHASE2-2025",
        "name": "ADA Atalpuram Township Phase 2 Residential Plot Lottery 2025 (Sectors 2 & 3)",
        "city": "Agra",
        "authority": "ADA",
        "status": "OPEN",
        "open_date": "2025-10-01",
        "close_date": "2026-03-31",
        "total_plots": 374,
        "price_min": 28.5,  # 40sqm × ₹29,500/sqm
        "price_max": 177.0,  # 600sqm × ₹29,500/sqm
        "area_sqft_min": 430,   # 40 sqm
        "area_sqft_max": 6458,  # 600 sqm
        "location_details": "Gwalior Highway — Kakua & Bhandai areas, Atalpuram Township, Agra",
        "apply_url": "https://www.adaagra.org.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/ada-agra-atal-puram-lottery",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "ADA-ATALPURAM-PHASE3-SECTOR8-2025",
        "name": "ADA Atalpuram Township Phase 3 Sector 8 Residential Plot Lottery 2025 (215 Plots)",
        "city": "Agra",
        "authority": "ADA",
        "status": "OPEN",
        "open_date": "2025-12-01",
        "close_date": "2026-02-28",
        "total_plots": 215,
        "price_min": 28.0,
        "price_max": 95.0,
        "area_sqft_min": 430,
        "area_sqft_max": 3229,
        "location_details": "Sector 8, Atalpuram Township, Gwalior Highway, Agra",
        "apply_url": "https://www.adaagra.org.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/ada-agra-atal-puram-lottery",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "ADA-ATALPURAM-PHASE1-2025",
        "name": "ADA Atalpuram Township Phase 1 Residential Plot Lottery 2025",
        "city": "Agra",
        "authority": "ADA",
        "status": "CLOSED",
        "open_date": "2025-07-01",
        "close_date": "2025-09-30",
        "total_plots": 374,
        "price_min": 28.0,
        "price_max": 88.0,
        "area_sqft_min": 430,
        "area_sqft_max": 3229,
        "location_details": "Sector 1, Atalpuram Township, Agra",
        "apply_url": "https://www.adaagra.org.in",
        "source_url": "https://www.adaagra.org.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 5. PRAYAGRAJ / PDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "PDA-RESIDENTIAL-OCT-2025",
        "name": "PDA Prayagraj Residential Plot Scheme 2025 (206 Plots via Online Lottery)",
        "city": "Prayagraj",
        "authority": "PDA",
        "status": "CLOSED",
        "open_date": "2025-09-26",
        "close_date": "2025-11-08",
        "total_plots": 206,
        "price_min": 25.0,
        "price_max": 85.0,
        "area_sqft_min": 646,   # 60 sqm
        "area_sqft_max": 4844,  # 450 sqm
        "location_details": "Various sectors, Prayagraj urban area",
        "apply_url": "http://www.pdaprayagraj.org",
        "source_url": "https://www.eauctionsindia.com/blog-details/pda-invites-bids-via-e-auction-for-plots-across-prayagraj-apply-online-now",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "PDA-UPCOMING-2026",
        "name": "PDA Prayagraj Residential Plot Lottery 2026 (Post-Kumbh Infrastructure Zone)",
        "city": "Prayagraj",
        "authority": "PDA",
        "status": "UPCOMING",
        "open_date": "2026-03-01",
        "close_date": "2026-05-31",
        "total_plots": 250,
        "price_min": 25.0,
        "price_max": 90.0,
        "area_sqft_min": 646,
        "area_sqft_max": 3229,
        "location_details": "Prayagraj Development Authority zone — multiple sectors",
        "apply_url": "http://www.pdaprayagraj.org",
        "source_url": "http://www.pdaprayagraj.org",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 6. CHANDIGARH / GMADA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "GMADA-ECOCITY2-EXT-2025",
        "name": "GMADA Eco City-2 Extension Residential Plot Draw Scheme 2025 (185 Plots)",
        "city": "Chandigarh",
        "authority": "GMADA",
        "status": "UPCOMING",
        "open_date": "2025-11-01",
        "close_date": "2026-01-31",
        "total_plots": 185,
        "price_min": 180.0,  # 500 sqyd × ₹60k/sqyd
        "price_max": 360.0,  # 1000 sqyd × ₹60k/sqyd
        "area_sqft_min": 4185,  # 500 sqyd (approx)
        "area_sqft_max": 8370,  # 1000 sqyd
        "location_details": "Eco City-2 Extension, New Chandigarh, Hoshiarpur Village, Mohali",
        "apply_url": "https://gmada.gov.in",
        "source_url": "https://garahpravesh.com/gmada-eco-city-2-plot-scheme-mohali-2025/",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "GMADA-ECOCITY2-289-2025",
        "name": "GMADA Eco City-2 New Chandigarh Residential Plots Draw 2025 (289 Plots)",
        "city": "Chandigarh",
        "authority": "GMADA",
        "status": "CLOSED",
        "open_date": "2025-01-01",
        "close_date": "2025-03-31",
        "total_plots": 289,
        "price_min": 60.0,
        "price_max": 300.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 21528,
        "location_details": "Eco City-2, New Chandigarh, SAS Nagar Mohali",
        "apply_url": "https://gmada.gov.in",
        "source_url": "https://gmada.gov.in/en/gmada-invites-applications-for-the-allotment-of-289-residential-plots-at-eco-city-2-new-chandigarh",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 7. NAVI MUMBAI / CIDCO
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "CIDCO-MY-PREFERRED-2024",
        "name": "CIDCO My Preferred Home Scheme 2024–25 — 26,502 Units (1L+ Applications)",
        "city": "Navi Mumbai",
        "authority": "CIDCO",
        "status": "CLOSED",
        "open_date": "2024-10-12",
        "close_date": "2025-01-30",
        "total_plots": 26502,
        "price_min": 35.0,
        "price_max": 200.0,
        "area_sqft_min": 323,
        "area_sqft_max": 700,
        "location_details": "Kharghar, Taloja, Panvel, Ulwe, Vashi, Khandeshwar, Dronagiri — Navi Mumbai",
        "apply_url": "https://cidcohomes.com",
        "source_url": "https://www.99acres.com/articles/cidco-lottery-2019-online-application-eligibility-results-draw-date-winner-list.html",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "CIDCO-PLOTS-NMIA-2025",
        "name": "CIDCO Leasehold Residential Plots Near Navi Mumbai International Airport 2025 (30 Plots)",
        "city": "Navi Mumbai",
        "authority": "CIDCO",
        "status": "UPCOMING",
        "open_date": "2026-01-01",
        "close_date": "2026-06-30",
        "total_plots": 30,
        "price_min": 80.0,
        "price_max": 300.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 3229,
        "location_details": "Near NMIA Airport site, Navi Mumbai",
        "apply_url": "https://cidcohomes.com",
        "source_url": "https://www.eauctionsindia.com/blog-details/cidco-plot-auction-2025-30-leasehold-plots-on-auction-near-nmia",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "CIDCO-MASS-HOUSING-2025",
        "name": "CIDCO Mass Housing Lottery 2025 — 22,000 Homes Pipeline (Incl. 16,000 Unsold Units)",
        "city": "Navi Mumbai",
        "authority": "CIDCO",
        "status": "UPCOMING",
        "open_date": "2025-06-01",
        "close_date": "2026-03-31",
        "total_plots": 22000,
        "price_min": 35.0,
        "price_max": 200.0,
        "area_sqft_min": 323,
        "area_sqft_max": 700,
        "location_details": "Vashi, Juinagar, Kharghar, Taloja, Dronagiri — Navi Mumbai",
        "apply_url": "https://cidcohomes.com",
        "source_url": "https://nayeghar.com/cidco-lottery-2025-complete-guide-to-22000-affordable-homes-in-navi-mumbai-eligibility-documents-registration-pricing/",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 8. HYDERABAD / HMDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "HMDA-LAYOUT-PLOTS-2025",
        "name": "HMDA Developed Layout Residential Plots 2025 (Miyapur, Keesara, Ghatkesar)",
        "city": "Hyderabad",
        "authority": "HMDA",
        "status": "ACTIVE",
        "open_date": "2025-01-01",
        "close_date": "2026-06-30",
        "total_plots": 500,
        "price_min": 30.0,
        "price_max": 200.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 5382,
        "location_details": "Miyapur, Keesara, Bachupally, Ghatkesar, RRR corridor — Hyderabad",
        "apply_url": "https://www.hmda.gov.in/hmda-dev-layout-plots/",
        "source_url": "https://www.hmda.gov.in/hmda-dev-layout-plots/",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "HMDA-RRR-CORRIDOR-2025",
        "name": "HMDA Regional Ring Road Corridor Residential Plot Lottery 2025–26",
        "city": "Hyderabad",
        "authority": "HMDA",
        "status": "UPCOMING",
        "open_date": "2026-01-01",
        "close_date": "2026-06-30",
        "total_plots": 400,
        "price_min": 35.0,
        "price_max": 150.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 5382,
        "location_details": "RRR buffer zone — 1355 villages under HMDA extension, Hyderabad",
        "apply_url": "https://www.hmda.gov.in",
        "source_url": "https://www.hmda.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 9. PUNE / PMRDA + MHADA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "PMRDA-HOUSING-LOTTERY-2025",
        "name": "PMRDA Housing Lottery 2025–26 (833 Units — EWS & LIG Plots)",
        "city": "Pune",
        "authority": "PMRDA",
        "status": "OPEN",
        "open_date": "2025-09-01",
        "close_date": "2026-04-09",
        "total_plots": 833,
        "price_min": 25.0,
        "price_max": 95.0,
        "area_sqft_min": 270,
        "area_sqft_max": 3229,
        "location_details": "Sector 12, PMC, PCMC and PMRDA peripheral nodes — Pune",
        "apply_url": "https://housing.pmrda.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/pmrda-lottery",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "MHADA-PUNE-2025",
        "name": "MHADA Pune Board Plot Lottery 2025 (6,294 Units including Plots)",
        "city": "Pune",
        "authority": "MHADA-PUNE",
        "status": "CLOSED",
        "open_date": "2024-11-01",
        "close_date": "2025-01-28",
        "total_plots": 6294,
        "price_min": 25.0,
        "price_max": 320.0,
        "area_sqft_min": 270,
        "area_sqft_max": 3229,
        "location_details": "Hadapsar, Pimpri-Chinchwad, Alandi, Shirur — Pune",
        "apply_url": "https://lottery.mhada.gov.in",
        "source_url": "https://www.99acres.com/articles/mhada-pune-lottery.html",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 10. BENGALURU / BDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "BDA-ARKAVATHY-2E-2026",
        "name": "BDA Arkavathy Layout 2E Residential Sites Lottery 2026 (5,000 Plots)",
        "city": "Bengaluru",
        "authority": "BDA",
        "status": "OPEN",
        "open_date": "2026-01-01",
        "close_date": "2026-04-30",
        "total_plots": 5000,
        "price_min": 55.0,
        "price_max": 350.0,
        "area_sqft_min": 646,
        "area_sqft_max": 5167,
        "location_details": "Arkavathy Layout, North Bangalore",
        "apply_url": "https://bdakarnataka.in/site-allotment/",
        "source_url": "https://bdakarnataka.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "BDA-KEMPEGOWDA-LAYOUT-2026",
        "name": "BDA Nadaprabhu Kempegowda Layout Residential Sites Lottery 2026",
        "city": "Bengaluru",
        "authority": "BDA",
        "status": "UPCOMING",
        "open_date": "2026-10-01",
        "close_date": "2026-12-31",
        "total_plots": 3200,
        "price_min": 60.0,
        "price_max": 280.0,
        "area_sqft_min": 646,
        "area_sqft_max": 2583,
        "location_details": "Kempegowda Layout, Bangalore",
        "apply_url": "https://bdakarnataka.in/site-allotment/",
        "source_url": "https://bdakarnataka.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "BDA-JPNAGAR-9TH-PHASE-2026",
        "name": "BDA JP Nagar 9th Phase Residential Plot Lottery 2026 (800 Plots)",
        "city": "Bengaluru",
        "authority": "BDA",
        "status": "UPCOMING",
        "open_date": "2026-07-01",
        "close_date": "2026-09-30",
        "total_plots": 800,
        "price_min": 90.0,
        "price_max": 500.0,
        "area_sqft_min": 1292,
        "area_sqft_max": 6458,
        "location_details": "JP Nagar 9th Phase, South Bangalore",
        "apply_url": "https://bdakarnataka.in/site-allotment/",
        "source_url": "https://bdakarnataka.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 11. RAIPUR / NRDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "NRDA-SECTOR30-DEC-2025",
        "name": "NRDA Sector-30 Nava Raipur Residential Plot Lottery (December Cycle 2025)",
        "city": "Raipur",
        "authority": "NRDA",
        "status": "CLOSED",
        "open_date": "2025-11-01",
        "close_date": "2025-12-31",
        "total_plots": 150,
        "price_min": 25.0,
        "price_max": 80.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 10764,
        "location_details": "Sector-30, Nava Raipur Atal Nagar Smart City, Raipur",
        "apply_url": "https://www.nava-raipur.com",
        "source_url": "https://www.tendersontime.com/authority/naya-raipur-development-authority-3718/",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "NRDA-RESIDENTIAL-2026",
        "name": "NRDA Nava Raipur Atal Nagar Residential Plot Lottery 2026",
        "city": "Raipur",
        "authority": "NRDA",
        "status": "UPCOMING",
        "open_date": "2026-03-01",
        "close_date": "2026-05-31",
        "total_plots": 200,
        "price_min": 25.0,
        "price_max": 80.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 10764,
        "location_details": "Nava Raipur Atal Nagar Smart City — various sectors",
        "apply_url": "https://www.nava-raipur.com",
        "source_url": "https://www.nava-raipur.com",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 12. VARANASI / VDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "VDA-RESIDENTIAL-2025",
        "name": "VDA Varanasi Residential Plot Lottery 2025",
        "city": "Varanasi",
        "authority": "VDA",
        "status": "CLOSED",
        "open_date": "2025-01-01",
        "close_date": "2025-06-30",
        "total_plots": 100,
        "price_min": 25.0,
        "price_max": 95.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 3229,
        "location_details": "Varanasi Development Authority zone — multiple sectors",
        "apply_url": "https://vdavns.com",
        "source_url": "https://vdavns.com",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "VDA-TRANSPORT-NAGAR-2025",
        "name": "VDA Transport Nagar Yojna Phase 1 Residential Plot Lottery 2025–26",
        "city": "Varanasi",
        "authority": "VDA",
        "status": "ACTIVE",
        "open_date": "2025-06-01",
        "close_date": "2026-03-31",
        "total_plots": 120,
        "price_min": 30.0,
        "price_max": 100.0,
        "area_sqft_min": 1076,
        "area_sqft_max": 3229,
        "location_details": "Transport Nagar, Varanasi — Kashi Vishwanath Corridor zone",
        "apply_url": "https://vdavns.com",
        "source_url": "https://vdavns.com",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 13. BHUBANESWAR / BDA ODISHA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "BDA-OD-PLOT-LOTTERY-2025",
        "name": "BDA Bhubaneswar Residential Plot Lottery 2025",
        "city": "Bhubaneswar",
        "authority": "BDA-OD",
        "status": "ACTIVE",
        "open_date": "2025-01-01",
        "close_date": "2026-06-30",
        "total_plots": 200,
        "price_min": 25.0,
        "price_max": 90.0,
        "area_sqft_min": 807,   # 75 sqm
        "area_sqft_max": 5382,  # 500 sqm
        "location_details": "Bhubaneswar urban zone and peripheral areas",
        "apply_url": "https://www.bda.gov.in",
        "source_url": "https://www.bda.gov.in/circular",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "BDA-OD-SUBHADRA-2025",
        "name": "BDA Bhubaneswar Subhadra Yojana Residential Plot Scheme 2025–26",
        "city": "Bhubaneswar",
        "authority": "BDA-OD",
        "status": "UPCOMING",
        "open_date": "2026-01-01",
        "close_date": "2026-06-30",
        "total_plots": 250,
        "price_min": 25.0,
        "price_max": 90.0,
        "area_sqft_min": 807,
        "area_sqft_max": 5382,
        "location_details": "Bhubaneswar — Smart City peripheral zones",
        "apply_url": "https://www.bda.gov.in",
        "source_url": "https://www.bda.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 14. NAGPUR / NIT
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "NIT-HINGNA-ROAD-2026",
        "name": "NIT Nagpur Hingna Road Residential Plot Lottery 2026 (650 Plots)",
        "city": "Nagpur",
        "authority": "NIT",
        "status": "OPEN",
        "open_date": "2026-02-01",
        "close_date": "2026-04-30",
        "total_plots": 650,
        "price_min": 28.0,
        "price_max": 80.0,
        "area_sqft_min": 969,   # 90 sqm
        "area_sqft_max": 4306,  # 400 sqm
        "location_details": "Hingna Road, Nagpur West",
        "apply_url": "https://nagpurimprovement.gov.in",
        "source_url": "https://nagpurimprovement.gov.in/schemes",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "NIT-MIHAN-TOWNSHIP-2026",
        "name": "NIT MIHAN Nagpur Residential Township Plot Lottery 2026 (1,500 Plots)",
        "city": "Nagpur",
        "authority": "NIT",
        "status": "UPCOMING",
        "open_date": "2026-08-01",
        "close_date": "2026-10-31",
        "total_plots": 1500,
        "price_min": 35.0,
        "price_max": 110.0,
        "area_sqft_min": 646,
        "area_sqft_max": 4306,
        "location_details": "MIHAN Nagpur International Airport Zone",
        "apply_url": "https://nagpurimprovement.gov.in",
        "source_url": "https://nagpurimprovement.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 15. AHMEDABAD / AUDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "AUDA-RESIDENTIAL-2025",
        "name": "AUDA Ahmedabad Residential Plot Lottery 2025",
        "city": "Ahmedabad",
        "authority": "AUDA",
        "status": "CLOSED",
        "open_date": "2025-01-01",
        "close_date": "2025-06-30",
        "total_plots": 300,
        "price_min": 30.0,
        "price_max": 120.0,
        "area_sqft_min": 861,   # 80 sqm
        "area_sqft_max": 5382,  # 500 sqm
        "location_details": "Ahmedabad periphery — GIFT City adjacent zones",
        "apply_url": "https://auda.org.in",
        "source_url": "https://auda.org.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "GUDA-GANDHINAGAR-2026",
        "name": "GUDA Gandhinagar Residential Plot Lottery 2026",
        "city": "Ahmedabad",
        "authority": "GUDA",
        "status": "UPCOMING",
        "open_date": "2026-04-01",
        "close_date": "2026-06-30",
        "total_plots": 400,
        "price_min": 30.0,
        "price_max": 120.0,
        "area_sqft_min": 861,
        "area_sqft_max": 5382,
        "location_details": "Gandhinagar — GIFT City sector",
        "apply_url": "https://auda.org.in",
        "source_url": "https://auda.org.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 16. DELHI / DDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "DDA-DWARKA-EXT-2026",
        "name": "DDA Dwarka Extension Residential Plot Lottery 2026",
        "city": "Delhi",
        "authority": "DDA",
        "status": "UPCOMING",
        "open_date": "2026-06-01",
        "close_date": "2026-08-31",
        "total_plots": 6000,
        "price_min": 60.0,
        "price_max": 600.0,
        "area_sqft_min": 582,   # 54 sqm
        "area_sqft_max": 3875,  # 360 sqm
        "location_details": "Dwarka Extension, South West Delhi",
        "apply_url": "https://dda.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/dda-housing-scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "DDA-NARELA-2025",
        "name": "DDA Jan Sadharan Awaas Yojana Narela Residential Plot Lottery 2025",
        "city": "Delhi",
        "authority": "DDA",
        "status": "CLOSED",
        "open_date": "2025-06-01",
        "close_date": "2025-08-31",
        "total_plots": 4500,
        "price_min": 45.0,
        "price_max": 320.0,
        "area_sqft_min": 484,
        "area_sqft_max": 2906,
        "location_details": "Narela, North Delhi — Phase I allotted Day 1",
        "apply_url": "https://dda.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/dda-housing-scheme",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "DDA-ROHINI-2026",
        "name": "DDA Rohini Residential Plot Lottery 2026",
        "city": "Delhi",
        "authority": "DDA",
        "status": "UPCOMING",
        "open_date": "2026-10-01",
        "close_date": "2026-12-31",
        "total_plots": 2800,
        "price_min": 55.0,
        "price_max": 450.0,
        "area_sqft_min": 582,
        "area_sqft_max": 3875,
        "location_details": "Rohini, North West Delhi",
        "apply_url": "https://dda.gov.in",
        "source_url": "https://dda.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 17. BHOPAL / VP-BPL
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "VP-BPL-MISROD-PHASE2-2025",
        "name": "BDA Bhopal Sardar Vallabhbhai Patel Misrod Phase-2 Residential Plot Sale 2025 (50 Plots)",
        "city": "Bhopal",
        "authority": "VP-BPL",
        "status": "CLOSED",
        "open_date": "2025-09-23",
        "close_date": "2025-10-08",
        "total_plots": 50,
        "price_min": 25.0,
        "price_max": 45.0,
        "area_sqft_min": 646,  # 60 sqm
        "area_sqft_max": 646,
        "location_details": "Misrod Phase-2, Bhopal",
        "apply_url": "https://vikaspradhikaran.mponline.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/bda-bhopal-residential-plot-sale",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "VP-BPL-AEROCITY-PHASE1-2025",
        "name": "BDA Bhopal Aerocity Phase-1 Residential Plot Sale 2025",
        "city": "Bhopal",
        "authority": "VP-BPL",
        "status": "CLOSED",
        "open_date": "2025-11-20",
        "close_date": "2025-12-08",
        "total_plots": 120,
        "price_min": 30.0,
        "price_max": 90.0,
        "area_sqft_min": 646,
        "area_sqft_max": 4306,
        "location_details": "Aerocity Phase-1, Bhopal",
        "apply_url": "https://vikaspradhikaran.mponline.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/bda-bhopal-residential-plot-sale",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "VP-BPL-NAVIBAGH-2026",
        "name": "BDA Bhopal Navibagh Affordable Residential Plot Scheme 2026",
        "city": "Bhopal",
        "authority": "VP-BPL",
        "status": "UPCOMING",
        "open_date": "2026-04-01",
        "close_date": "2026-06-30",
        "total_plots": 200,
        "price_min": 28.0,
        "price_max": 80.0,
        "area_sqft_min": 646,
        "area_sqft_max": 3229,
        "location_details": "Navibagh Affordable Scheme, Bhopal",
        "apply_url": "https://vikaspradhikaran.mponline.gov.in",
        "source_url": "https://vikaspradhikaran.mponline.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 18. UDAIPUR / UIT
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "UIT-DIWALI-ELOTTERY-2025",
        "name": "UIT Udaipur Diwali Special E-Lottery 2025 — 1,109 Residential Plots (RERA-Compliant)",
        "city": "Udaipur",
        "authority": "UIT",
        "status": "CLOSED",
        "open_date": "2025-10-07",
        "close_date": "2025-11-07",
        "total_plots": 1109,
        "price_min": 25.0,   # ₹1,190/sqm is very affordable
        "price_max": 80.0,
        "area_sqft_min": 807,
        "area_sqft_max": 5382,
        "location_details": "Multiple RERA-registered locations, Udaipur — City of Lakes",
        "apply_url": "https://uitudaipur.org",
        "source_url": "https://www.eauctionsindia.com/blog-details/udaipur-uda-lottery",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "UIT-RESIDENTIAL-2026",
        "name": "UIT Udaipur Residential Plot E-Lottery 2026",
        "city": "Udaipur",
        "authority": "UIT",
        "status": "UPCOMING",
        "open_date": "2026-10-01",
        "close_date": "2026-11-30",
        "total_plots": 500,
        "price_min": 25.0,
        "price_max": 80.0,
        "area_sqft_min": 807,
        "area_sqft_max": 5382,
        "location_details": "Udaipur — South Extension Balicha and other approved locations",
        "apply_url": "https://uitudaipur.org",
        "source_url": "https://uitudaipur.org",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 19. DEHRADUN / MDDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "MDDA-RESIDENTIAL-2025",
        "name": "MDDA Dehradun Residential Plot Lottery 2025",
        "city": "Dehradun",
        "authority": "MDDA",
        "status": "CLOSED",
        "open_date": "2025-01-01",
        "close_date": "2025-09-30",
        "total_plots": 120,
        "price_min": 30.0,
        "price_max": 150.0,
        "area_sqft_min": 646,
        "area_sqft_max": 4306,
        "location_details": "Dehradun urban zone — MDDA jurisdiction",
        "apply_url": "http://mddaonline.in",
        "source_url": "http://mddaonline.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "MDDA-DHAULAS-YOJANA-2024",
        "name": "MDDA Dehradun Dhaulaas Aawasiya Yojna Residential Plot Lottery 2024",
        "city": "Dehradun",
        "authority": "MDDA",
        "status": "CLOSED",
        "open_date": "2024-08-05",
        "close_date": "2024-09-04",
        "total_plots": 100,
        "price_min": 30.0,
        "price_max": 150.0,
        "area_sqft_min": 646,
        "area_sqft_max": 3229,
        "location_details": "Aamwala Tarla, Dehradun",
        "apply_url": "http://mddaonline.in",
        "source_url": "http://mddaonline.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "MDDA-UPCOMING-2026",
        "name": "MDDA Dehradun Residential Plot Lottery 2026 (Upcoming)",
        "city": "Dehradun",
        "authority": "MDDA",
        "status": "UPCOMING",
        "open_date": "2026-04-01",
        "close_date": "2026-06-30",
        "total_plots": 150,
        "price_min": 35.0,
        "price_max": 150.0,
        "area_sqft_min": 646,
        "area_sqft_max": 4306,
        "location_details": "Dehradun — MDDA planning zone",
        "apply_url": "http://mddaonline.in",
        "source_url": "http://mddaonline.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },

    # ═══════════════════════════════════════════════════════════════════
    # 20. MEERUT / MDA
    # ═══════════════════════════════════════════════════════════════════
    {
        "scheme_id": "MDA-NEW-SCHEME-2025",
        "name": "MDA Meerut New Residential Plot Scheme 2025 (RRTS Corridor Zone)",
        "city": "Meerut",
        "authority": "MDA",
        "status": "CLOSED",
        "open_date": "2025-01-01",
        "close_date": "2025-06-30",
        "total_plots": 300,
        "price_min": 30.0,
        "price_max": 90.0,
        "area_sqft_min": 538,   # 50 sqm
        "area_sqft_max": 5382,  # 500 sqm
        "location_details": "Meerut city — NCR RRTS corridor influenced zone",
        "apply_url": "https://mda.up.gov.in",
        "source_url": "https://www.eauctionsindia.com/blog-details/mda-meerut",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
    {
        "scheme_id": "MDA-UPCOMING-2026",
        "name": "MDA Meerut Residential Plot Lottery 2026 (Delhi-Meerut RRTS Corridor)",
        "city": "Meerut",
        "authority": "MDA",
        "status": "UPCOMING",
        "open_date": "2026-03-01",
        "close_date": "2026-05-31",
        "total_plots": 350,
        "price_min": 30.0,
        "price_max": 90.0,
        "area_sqft_min": 538,
        "area_sqft_max": 5382,
        "location_details": "Meerut — NCR spillover demand zone, RRTS Phase 1 corridor",
        "apply_url": "https://mda.up.gov.in",
        "source_url": "https://mda.up.gov.in",
        "data_source": "STATIC",
        "scraper_status": "fallback",
        "last_updated": _now(),
        "is_active": True,
    },
]


def get_schemes_for_city(city: str) -> list[dict]:
    """Return static schemes for a specific city."""
    return [s for s in STATIC_SCHEMES if s["city"] == city]


def get_all_static_schemes() -> list[dict]:
    """Return all static schemes."""
    return STATIC_SCHEMES.copy()
